-- KHÁCH HÀNG
CREATE TABLE khachhang (
    MAKH VARCHAR(100) PRIMARY KEY,
    TENKH VARCHAR(100),
    SODIENTHOAI VARCHAR(100)
);

-- NHÂN VIÊN
CREATE TABLE nhanvien (
    MANV VARCHAR(100) PRIMARY KEY,
    MATKHAU VARCHAR(100),
    HOTENNV VARCHAR(100),
    EMAIL VARCHAR(100),
    SOCCCD VARCHAR(100),
    VITRILAM VARCHAR(100)
);

-- ĐỒ UỐNG
CREATE TABLE douong (
    MADOUONG VARCHAR(100) PRIMARY KEY,
    TENDOUONG VARCHAR(100),
    LOAIDOUONG VARCHAR(100),
    GIADOUONG DECIMAL(10,2),
    TRANGTHAI BOOLEAN
);

-- LỊCH LÀM VIỆC (một mã lịch có thể có nhiều khung giờ)
CREATE TABLE lichlamviec ( 
    MALLV VARCHAR(100),
    MANV VARCHAR(100),
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
    THOIGIANBATDAU TIME,
    THOIGIANKETHUC TIME,
    PRIMARY KEY (MALLV, THOIGIANBATDAU, THOIGIANKETHUC),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);


-- HÓA ĐƠN
CREATE TABLE hoadon (
    MAHD VARCHAR(100) PRIMARY KEY,
    MAKH VARCHAR(100),
    MANV VARCHAR(100),
    NGAYMUA DATETIME,
    TONGTIEN DECIMAL(10,2),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
);

-- CHI TIẾT HÓA ĐƠN
CREATE TABLE chitiethoadon (
    MAHD VARCHAR(100),
    MADOUONG VARCHAR(100),
    SOLUONG INT,
    DONGIA DECIMAL(10,2),
    THANHTIEN DECIMAL(10,2)
    PRIMARY KEY (MAHD, MADOUONG),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    FOREIGN KEY (MADOUONG) REFERENCES DOUONG(MADOUONG)
);
