-- KHÁCH HÀNG
create TABLE khachhang (
    MAKH VARCHAR(100) PRIMARY KEY,
    TENKH VARCHAR(100),
    SODIENTHOAI VARCHAR(100)
);

-- NHÂN VIÊN
create TABLE nhanvien (
    MANV VARCHAR(100) PRIMARY KEY,
    MATKHAU VARCHAR(100),
    HOTENNV VARCHAR(100),
    EMAIL VARCHAR(100),
    SOCCCD VARCHAR(100),
    VITRILAM VARCHAR(100),
    ROLE ENUM('EMPLOYEE', 'ADMIN') NOT NULL,
    LUONG DECIMAL(10,2)
);
select * from nhanvien
select * from lichlamviec
//không có trong DB
ALTER TABLE nhanvien ADD COLUMN ROLE ENUM('EMPLOYEE', 'ADMIN') NOT NULL
ALTER TABLE nhanvien ADD COLUMN LUONG DECIMAL(10,2) NOT NULL
SELECT * FROM lichlamviec;
ALTER TABLE nhanvien CHANGE COLUMN SODIENTHOAI SODIENTHOAI VARCHAR(255)
-- ĐỒ UỐNG
create TABLE douong (
    MADOUONG VARCHAR(100) PRIMARY KEY,
    TENDOUONG VARCHAR(100),
    LOAIDOUONG VARCHAR(100),
    GIADOUONG DECIMAL(10,2),
    TRANGTHAI BOOLEAN
);

-- LỊCH LÀM VIỆC (một mã lịch có thể có nhiều khung giờ)
create TABLE lichlamviec (
    id VARCHAR(100),
    NVTAOLICH VARCHAR(100),
    MANV VARCHAR(100),
    NGAYBATDAU VARCHAR(100),
    NGAYKETTHUC VARCHAR(100),
    THOIGIANBATDAU VARCHAR(100),
    THOIGIANKETHUC VARCHAR(100),
    SOLUONG INT
    PRIMARY KEY (id),
    FOREIGN KEY (MANV) REFERENCES nhanvien(MANV)
);
//chỉ cần tạo một khoá ngoại tổng hợp
create TABLE dangky (
    MALLV VARCHAR(100),
    MANV VARCHAR(100),
    PRIMARY KEY (MALLV, MANV),
    FOREIGN KEY (MALLV) REFERENCES lichlamviec(id),
    FOREIGN KEY (MANV) REFERENCES nhanvien(MANV)
);

// tạo trigger cho bảng

CREATE TRIGGER trg_check_soluong_before_insert
BEFORE INSERT ON dangky
FOR EACH ROW
BEGIN
    DECLARE so_con_lai INT DEFAULT 0;
    SELECT SOLUONG INTO so_con_lai FROM lichlamviec WHERE id = NEW.MALLV;
    IF so_con_lai <= 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Không thể đăng ký: ca làm đã đủ người';
    END IF;
END;


CREATE TRIGGER trg_giam_soluong_after_insert
AFTER INSERT ON dangky
FOR EACH ROW
BEGIN
    UPDATE lichlamviec SET SOLUONG = SOLUONG - 1 WHERE id = NEW.MALLV;
END;

CREATE TRIGGER trg_tang_soluong_after_delete
AFTER DELETE ON dangky
FOR EACH ROW
BEGIN
    UPDATE lichlamviec SET SOLUONG = SOLUONG + 1 WHERE id = OLD.MALLV;
END;


//không có trong db
SELECT
    SUM(TIMESTAMPDIFF(MINUTE,
                      STR_TO_DATE(l.THOIGIANBATDAU, '%H:%i'),
                      STR_TO_DATE(l.THOIGIANKETHUC, '%H:%i'))) / 60 AS tong_gio_lam
FROM dangky dk
JOIN lichlamviec l ON dk.maLlv = l.id
WHERE dk.maNv = :maNv
drop table dangky
drop table lichlamviec
select * from nhanvien;
ALTER TABLE lichlamviec CHANGE COLUMN MANV NVTAOLICH VARCHAR(100)
ALTER TABLE lichlamviec CHANGE COLUMN MALLV id VARCHAR(100)
ALTER TABLE lichlamviec ADD COLUMN SOLUONG INT
ALTER TABLE lichlamviec MODIFY COLUMN NGAYBATDAU VARCHAR(100)
ALTER TABLE lichlamviec MODIFY COLUMN NGAYKETTHUC VARCHAR(100)
ALTER TABLE lichlamviec MODIFY COLUMN THOIGIANBATDAU VARCHAR(100)
ALTER TABLE lichlamviec MODIFY COLUMN THOIGIANKETHUC VARCHAR(100)
DELETE FROM lichlamviec where NGAYBATDAU is null
-- HÓA ĐƠN
create TABLE hoadon (
    MAHD VARCHAR(100) PRIMARY KEY,
    MAKH VARCHAR(100),
    MANV VARCHAR(100),
    NGAYMUA DATETIME,
    TONGTIEN DECIMAL(10,2),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
);

-- CHI TIẾT HÓA ĐƠN
create TABLE chitiethoadon (
    MAHD VARCHAR(100),
    MADOUONG VARCHAR(100),
    SOLUONG INT,
    DONGIA DECIMAL(10,2),
    THANHTIEN DECIMAL(10,2)
    PRIMARY KEY (MAHD, MADOUONG),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    FOREIGN KEY (MADOUONG) REFERENCES DOUONG(MADOUONG)
);


